- name: Gather and print local facts
  hosts: regions:ap_northeast_2:az_a:dev
  become: true
  gather_facts: true
  tasks:
    - name: Print facts
      ansible.builtin.debug:
        var: ansible_facts
